mkdir actions-runner; cd actions-runner
Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.299.1/actions-runner-win-x64-2.299.1.zip -OutFile actions-runner-win-x64-2.299.1.zip
if((Get-FileHash -Path actions-runner-win-x64-2.299.1.zip -Algorithm SHA256).Hash.ToUpper() -ne 'f7940b16451d6352c38066005f3ee6688b53971fcc20e4726c7907b32bfdf539'.ToUpper()){ throw 'Computed checksum did not match' }
Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/actions-runner-win-x64-2.299.1.zip", "$PWD")
./config.cmd --url https://github.com/asuobj/I-like-you --token A2X2MSULNAJSEXOBJ4I7ZZ3DRQZQK
./run.cmd
runs-on: self-hosted
